apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-sa1-eks-cluster
  region: us-east-1

vpc:
  id: vpc-0b24229ca25488d6c
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-EKS-VPC-stack-PublicSubnet01:
        id: subnet-06278b40076cf705e
      my-EKS-VPC-stack-PublicSubnet02:
        id: subnet-0fb1edae07559d754
    private:
      my-EKS-VPC-stack-PrivateSubnet01:
        id: subnet-05e969185d67053bf
      my-EKS-VPC-stack-PrivateSubnet02:
        id: subnet-0d0b1437214ef41cf

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 1
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true

#eksctl create cluster -f cluster.yaml
