on:
  push:
  
name: env-var btwn jobs

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        sudo EXPORT PORT='1234'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    
    - run: | 
        echo $PORT

