on:
  push:
  
name: env-var btwn jobs

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        export PORT=1234 >> $GITHUB_ENV
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    
    - run: | 
        echo $env.PORT

