on:
  push:
  
name: env-var btwn jobs

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        export ID=234344
        echo $ID
        echo 'IDD=$ID' >> $GITHUB_ENV
        export PORT=1234 >> $GITHUB_ENV
        echo ${{env.PORT}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    
    - run: | 
        echo $IDD
        echo ${{env.PORT}}

