on:
  push:
  
name: env-var btwn jobs

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    
#     - run: |
#         ID=234344
        
#         echo 'IDD=$ID' >> $GITHUB_ENV
#         export PORT=1234 >> $GITHUB_ENV
#         echo "port env variable ->" ${{env.PORT}}
#     - run: |
#         echo "the env var from previous step is --> " ${{env.IDD}}
        
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}"
    
    - id: send to another job
      run: |
        echo "test=hello" >> $GITHUB_OUTPUT
    - id: send to another job 2
      run: |
        world="sawan"
        echo "test=$world" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    
    - run: | 
        #echo "the env var from previous job is --> " ${{env.IDD}}
        #echo ${{env.PORT}}
        echo "the env var from previous job is -->" "${{ env.action_state }}"
        echo "${{ env.action_state }}"

