on:
  push:
  
name: env-var btwn jobs

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    
    - run: |
        ID=234344
        
        echo 'IDD=$ID' >> $GITHUB_ENV
        export PORT=1234 >> $GITHUB_ENV
        echo "port env variable ->" ${{env.PORT}}
    - run: |
        echo "the env var from previous step is --> " ${{env.IDD}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    
    - run: | 
        echo "the env var from previous job is --> " ${{env.IDD}}
        echo ${{env.PORT}}

